package col.com.w73.agenda.vista;

import col.com.w73.agenda.controlador.*;
import col.com.w73.agenda.modelo.Tarea;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class VistaAgenda extends javax.swing.JFrame {

    /**
     * Creates new form VistaAgenda
     */
    public Tarea tarea;
    public IControladorTareas controlador = new ControladorTareasImpl();
    public DefaultListModel modelo = new DefaultListModel();

    public VistaAgenda() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.outListaTareas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        PanelSuperior = new javax.swing.JPanel();
        btnSalir = new javax.swing.JLabel();
        btnAgregarTarea = new javax.swing.JButton();
        inputMinuto = new javax.swing.JComboBox<>();
        inputTarea = new javax.swing.JTextField();
        inputHoras = new javax.swing.JComboBox<>();
        dosPuntos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outListaTareas = new javax.swing.JList<>();
        btnBorrarTodo = new javax.swing.JButton();
        btnActualizarTarea = new javax.swing.JButton();
        btnListarTareas = new javax.swing.JButton();
        btnBorrarTarea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BackGround.setBackground(new java.awt.Color(44, 118, 149));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Agenda del dia!");

        PanelSuperior.setBackground(new java.awt.Color(29, 55, 82));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 255, 255));
        btnSalir.setText("X");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(16, 16, 16))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAgregarTarea.setText("Agregar Tarea");
        btnAgregarTarea.setBorder(null);
        btnAgregarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarTareaMouseClicked(evt);
            }
        });

        inputMinuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "15", "30", "45" }));

        inputHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        inputHoras.setBorder(new javax.swing.border.MatteBorder(null));

        dosPuntos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dosPuntos.setForeground(new java.awt.Color(0, 0, 0));
        dosPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dosPuntos.setText(":");

        outListaTareas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        outListaTareas.setMinimumSize(new java.awt.Dimension(200, 100));
        jScrollPane2.setViewportView(outListaTareas);

        btnBorrarTodo.setText("Borrar toda la agenda");
        btnBorrarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarTodoMouseClicked(evt);
            }
        });

        btnActualizarTarea.setText("Actualizar Tarea");
        btnActualizarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarTareaMouseClicked(evt);
            }
        });

        btnListarTareas.setText("Mostrar Tareas");
        btnListarTareas.setActionCommand("");
        btnListarTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarTareasMouseClicked(evt);
            }
        });

        btnBorrarTarea.setText("Borrar Tarea");
        btnBorrarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarTareaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(inputHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dosPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnBorrarTodo)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addComponent(PanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosPuntos)
                    .addComponent(btnAgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(btnListarTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        this.btnSalir.setForeground(Color.red);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        this.btnSalir.setForeground(new java.awt.Color(205, 255, 255));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnAgregarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarTareaMouseClicked
        if (this.inputTarea.getText().equals("") || this.inputTarea.getText().contains(",")) {
            JOptionPane.showMessageDialog(null, "Este compo no puede quedar vacio ni contener comas");
        } else {
            String hora;
            hora = this.inputHoras.getSelectedItem().toString() + ":" + this.inputMinuto.getSelectedItem().toString();
            tarea = new Tarea(hora, this.inputTarea.getText());
            controlador.IngresarTarea(tarea);
            this.inputTarea.setText("");
            this.inputTarea.requestFocus();
            modelo.addElement(tarea.toString());

        }
    }//GEN-LAST:event_btnAgregarTareaMouseClicked

    private void btnListarTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarTareasMouseClicked
        this.listarTodo();
    }//GEN-LAST:event_btnListarTareasMouseClicked
    private void listarTodo() {
        if (this.controlador.TieneContenido()) {
            List<Tarea> tareas = this.controlador.MostarTareas();
            modelo.removeAllElements();
            for (Tarea t : tareas) {
                modelo.addElement(t.toString());
            }
        } else {

            JOptionPane.showMessageDialog(null, "No hay tareas para mostrar");
        }
    }
    private void btnBorrarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarTodoMouseClicked
        modelo.removeAllElements();
        this.controlador.BorrarAgenda();
    }//GEN-LAST:event_btnBorrarTodoMouseClicked

    private void btnActualizarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTareaMouseClicked

        if (!this.outListaTareas.isSelectionEmpty()) {

            String tareaSelec = this.outListaTareas.getSelectedValue();
            String[] atributosTareaSelec = tareaSelec.split(",");
            Tarea tareaSel = new Tarea(atributosTareaSelec[0], atributosTareaSelec[1]);
            int indexTareaSelec = this.controlador.BuscarTarea(tareaSel);
            this.controlador.ActualizarTarea(IngresarNuevaTarea(), indexTareaSelec);
            modelo.removeAllElements();
            this.listarTodo();
        }

    }//GEN-LAST:event_btnActualizarTareaMouseClicked
    private Tarea IngresarNuevaTarea() {
        String[] horas = new String[24 * 4];
        String hora, descripcion;
        for (int i = 0, k = 0; i < horas.length && k < 24; i += 4, k++) {
            for (int j = 0, p = 0; j <= 45 && p < 4; j += 15, p++) {

                hora = (k + ":" + j);
                horas[i + p] = hora;
            }
        }
        Object obj;

        do {

            obj = JOptionPane.showInputDialog(null, "Ingrese la Hora", "Hora", JOptionPane.WARNING_MESSAGE, null, horas, 0);

        } while (obj == null);

        hora = obj.toString();

        do {

            descripcion = JOptionPane.showInputDialog(null, "Ingrese la tarea para realiar a las " + hora + " horas : ");

        } while (descripcion.equals("") || descripcion.contains(","));

        Tarea tareaNueva = new Tarea(hora, descripcion);
        return tareaNueva;

    }

    private void btnBorrarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarTareaMouseClicked
        if (!this.outListaTareas.isSelectionEmpty()) {

            String tareaSelec = this.outListaTareas.getSelectedValue();
            String[] atributosTareaSelec = tareaSelec.split(",");
            Tarea tareaSel = new Tarea(atributosTareaSelec[0], atributosTareaSelec[1]);
            int indexTareaSelec = this.controlador.BuscarTarea(tareaSel);
            this.controlador.BorrarTarea(indexTareaSelec);
            modelo.removeAllElements();
            this.listarTodo();
        }
    }//GEN-LAST:event_btnBorrarTareaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAgenda().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnActualizarTarea;
    private javax.swing.JButton btnAgregarTarea;
    private javax.swing.JButton btnBorrarTarea;
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnListarTareas;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel dosPuntos;
    private javax.swing.JComboBox<String> inputHoras;
    private javax.swing.JComboBox<String> inputMinuto;
    private javax.swing.JTextField inputTarea;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> outListaTareas;
    // End of variables declaration//GEN-END:variables
}
